changelog:
  categories:
    - title: "✨ Features"
      labels:
        - feat
    - title: "🐛 Fixes"
      labels:
        - fix
        - bug
    - title: "📄 Docs"
      labels:
        - docs
    - title: "Other"
      labels:
        - "*"
