[versions]
annotations = "24.1.0"
velocity = "3.3.0-SNAPSHOT"
gson = "2.11.0"
jda = "5.0.0-beta.24"

[libraries]
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
