[keys]
# Key lifetime in seconds.
lifetime = 10

[sessions]
# Session lifetime in seconds.
# If you specify zero or a negative value, the session will not be created.
lifetime = 600

[servers]
# The name of the server the player will be on during auth.
# Please note that this field cannot be empty.
limbo = "limbo"

# The name of the server the player will be redirected to after successful auth.
# If you leave this field blank, no redirection will occur.
redirect = ""

[discord]
# Your Discord bot's token.
token = ""

# List of Discord user IDs that will have access to bot commands.
ids = [""]

# Discord bot activity. Only the following activities will work: custom, competing, listening, playing, watching.
# If you specify an empty string or anything else, the activity will not be applied.
activity = "custom"
name = "https://github.com/orewaee/discord-auth/"
